# Generated by Django 5.0.2 on 2024-02-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_product_image_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
